# Name the Workflow
name: ArmTemplateDeployment

# Controls when the workflow will run
on:
#  push:
#    branches:
#      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  armDeploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Logs in to Azure with a GitHub secret
      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.Azure_Credentials }}
      # Deploys the template with the ARM template action 
      - name: Deploy Rescource Group from template
        uses: Azure/arm-deploy@v1
        with:
          scope: subscription
          subscriptionid: ${{ secrets.Sub_ID }}
          region: West Europe
          template: ./arm-templates/RSG.json
          deploymentName: DeployWithArmAction

      - name: Deploy Storage Account from template
        uses: Azure/arm-deploy@v1
        id: storageAccountDeploy
        with:
          scope: resourcegroup
          resourcegroupname: AxelDevOpsTesting
          subscriptionid: ${{ secrets.Sub_ID }}
          template: ./arm-templates/SA.json
          parameters: 
           ./arm-templates/SA.parameters.json
           StorageAccountName=axeldevopstestsa2
           location=northeurope
          deploymentMode: incremental # The default mode; will not edit resources already in the RG.


      - name: Deploy VM from template
        uses: Azure/arm-deploy@v1
        with:
          scope: resourcegroup
          resourcegroupname: AxelDevOpsTesting
          subscriptionid: ${{ secrets.Sub_ID }}
          template: ./arm-templates/VM.json
          parameters: 
            adminPassword=${{ secrets.UBUNTU_ADMIN_PASSWORD }}
            location=northeurope
          deploymentMode: incremental 



#      - run: echo ${{ steps.storageAccountDeploy.outputs.BlobUri }}


##        Deploying the template with az cli script!
#    - name: Deploy Resource Group from template with AZ CLI
#      uses: Azure/cli@1.0.4
#      with: 
#         inlinescript: |
#           az deployment sub create --location "West Europe" --template-file ./arm-templates/RSG.json
#